name: netlify
description: >-
  Dynamically generate _headers and _redirects files for Netlify in your Nuxt.js
  projects.
long_description: ''
repo: bazzite/nuxt-netlify
npm: '@aceforth/nuxt-netlify'
type: module
github: 'https://github.com/bazzite/nuxt-netlify'
website: 'https://github.com/bazzite/nuxt-netlify'
keywords:
  - external
categories:
  - deployment
maintainers:
  - name: bazzite
    github: bazzite
    avatar: 'https://github.com/bazzite.png'
