name: netlify-files
description: >-
  Nuxt module to create new _headers, _redirects and netlify.toml files for
  Netlify or to use existing ones
long_description: ''
repo: nuxt-community/netlify-files-module
npm: '@nuxtjs/netlify-files'
type: module
github: 'https://github.com/nuxt-community/netlify-files-module'
website: 'https://github.com/nuxt-community/netlify-files-module'
keywords:
  - community
categories: []
maintainers:
  - name: Alexander Lichter
    github: manniL
    twitter: TheAlexLichter
    avatar: 'https://github.com/manniL.png'
