repo: nuxt-community/applicationinsights-module
github: 'https://github.com/nuxt-community/applicationinsights-module'
website: 'https://github.com/nuxt-community/applicationinsights-module'
description: AppInsights module for Nuxt.js
license: MIT
module: {}
labels:
  - community
maintainers: []
npm_name: '@nuxtjs/applicationinsights'
