repo: nuxt-community/applicationinsights-module
github: 'https://github.com/nuxt-community/applicationinsights-module'
description: AppInsights module for Nuxt.js
license: MIT
module: {}
npm_name: '@nuxtjs/applicationinsights'
