repo: nuxt-community/netlify-files-module
github: 'https://github.com/nuxt-community/netlify-files-module'
website: 'https://github.com/nuxt-community/netlify-files-module'
module: {}
npm:
  name: '@nuxtjs/netlify-files'
  description: >-
    Nuxt module to create new _headers, _redirects and netlify.toml files for
    Netlify or to use existing ones
  license: MIT
labels:
  - community
maintainers: []
