name: applicationinsights
description: AppInsights module for Nuxt.js
long_description: ''
repo: nuxt-community/applicationinsights-module
npm: '@nuxtjs/applicationinsights'
keywords:
  - community
categories: []
maintainers: []
github: 'https://github.com/nuxt-community/applicationinsights-module'
website: 'https://github.com/nuxt-community/applicationinsights-module'
