name: sync

on: [pull_request, pull_request_target]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate' }}

    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --non-interactive

      - name: Sync
        run: yarn sync

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action
        with:
          commit_message: "chore: sync"
          file_pattern: "*.yml"
